// Content for the MineColonies helper page. Checked against MineColonies 1.1.1396 and the server's
// minecolonies-server.toml; names match what players see in game.
window.MC = {
  stages: [
    { id: 1, name: 'Sống sót', goal: 'Có thợ xây, nhà ở, gỗ và thức ăn' },
    { id: 2, name: 'Kho vận', goal: 'Đồ tự chạy giữa các công trình' },
    { id: 3, name: 'Ăn uống', goal: 'Bữa ăn tốt, thêm dân mới' },
    { id: 4, name: 'An ninh', goal: 'Sẵn sàng cho raid đầu tiên' },
    { id: 5, name: 'Mở rộng', goal: 'Chữa bệnh, dạy trẻ, dân vui' },
    { id: 6, name: 'Nâng cao', goal: 'Nghiên cứu và công trình hiếm' }
  ],

  buildings: [
    { id: 'townhall', name: 'Town Hall', img: 'townhall', stage: 1,
      role: 'Trung tâm của làng. Tạo thuộc địa, quản lý quyền hạn, xem danh sách dân và thống kê.',
      needs: 'Đặt từ Supply Camp. Bấm Build để thợ xây dựng thành toà nhà thật.',
      tips: ['Cấp Town Hall giới hạn cấp của hầu hết công trình khác.', 'Tab Permissions: thêm bạn bè và chọn họ được làm gì.', 'Cấp 3 mở dịch chuyển tới làng đồng minh.'],
      issues: ['guest-hostile', 'border'] },
    { id: 'builder', name: "Builder's Hut", img: 'builder', stage: 1,
      role: 'Nhà của thợ xây. Không có nó thì không công trình nào được xây, kể cả Town Hall.',
      needs: 'Gỗ, đá và vật liệu theo từng bản thiết kế.',
      tips: ['Builder\'s Hut phải có cấp bằng hoặc cao hơn công trình nó xây.', 'Nâng lên cấp 2 hoặc 3 sớm.', 'Làng đông thì xây thêm cái thứ hai để hai thợ làm song song.'],
      issues: ['builder-idle'] },
    { id: 'residence', name: 'Residence', img: 'residence', stage: 1,
      role: 'Nhà ở của dân. Mỗi cấp thêm 1 giường, tối đa 5 người ở cấp 5.',
      needs: 'Vật liệu xây theo style đã chọn.',
      tips: ['Dân mới chỉ tới và trẻ chỉ ra đời khi còn giường trống.', 'Nhà cấp cao làm dân vui hơn.'],
      issues: ['no-children', 'unhappy'] },
    { id: 'forester', name: "Forester's Hut", img: 'forester', stage: 1,
      role: 'Chặt cây và trồng lại. Nguồn gỗ chính của làng.',
      needs: 'Rìu và cây giống.',
      tips: ['Dùng Forest Tool để khoanh vùng rừng cho thợ.', 'Gỗ là thứ làng cần nhiều nhất lúc đầu.'],
      issues: ['builder-idle'] },
    { id: 'farmer', name: 'Farm', img: 'farmer', stage: 1,
      role: 'Trồng trọt trên các ô ruộng (Field). Nguồn lương thực.',
      needs: 'Cuốc và hạt giống.',
      tips: ['Đặt Field quanh Farm và chọn cây trồng cho từng ô.', 'Trồng nhiều loại để dân ăn đa dạng.'],
      issues: ['unhappy'] },
    { id: 'warehouse', name: 'Warehouse', img: 'warehouse', stage: 2, flow: 'hub',
      role: 'Kho trung tâm. Mọi đồ trong làng đi qua đây.',
      needs: 'Rack (kệ chứa) theo bản thiết kế; nâng cấp để thêm chỗ.',
      tips: ['Muốn đưa đồ cho cả làng: bỏ vào Warehouse, đừng bỏ vào rương ngoài.', 'Có thể nối băng chuyền Create đổ thẳng vào.'],
      issues: ['chest-ignored', 'slow-delivery'] },
    { id: 'courier', name: "Courier's Hut", img: 'courier', stage: 2,
      role: 'Người giao hàng: chở đồ từ Warehouse tới thợ và chở sản phẩm về kho.',
      needs: 'Không cần gì đặc biệt.',
      tips: ['Làng lớn cần 2 đến 4 Courier.', 'Thợ hay đứng "chờ" là dấu hiệu thiếu Courier.'],
      issues: ['slow-delivery'] },
    { id: 'miner', name: 'Mine', img: 'miner', stage: 2,
      role: 'Đào đá và quặng theo từng tầng.',
      needs: 'Cuốc đúng cấp, đuốc, gỗ chống hầm.',
      tips: ['Chọn tầng đào trong giao diện Mine.', 'Mỗi block đá có 1% ra quặng may mắn (thiết lập server).'],
      issues: ['miner-idle'] },
    { id: 'cook', name: 'Dining Hall', img: 'cook', stage: 3,
      role: 'Nấu ăn và phát bữa ăn cho dân.',
      needs: 'Nguyên liệu thô (thịt, cá, rau) và nhiên liệu.',
      tips: ['Bữa ăn nấu chín giúp dân vui và khoẻ hơn.', 'Kết hợp Bakery để có bánh mì.'],
      issues: ['unhappy'] },
    { id: 'tavern', name: 'Tavern', img: 'tavern', stage: 3,
      role: 'Chỗ ở ban đầu và nơi khách trọ ghé qua. Tuyển khách thành dân.',
      needs: 'Món đồ mà từng khách đòi.',
      tips: ['Cách nhanh nhất để có thêm dân ngay.', 'Có tỉ lệ nhỏ khách cầm đồ rồi bỏ trốn.'],
      issues: ['no-children', 'no-trade'] },
    { id: 'guardtower', name: 'Guard Tower', img: 'guardtower', stage: 4,
      role: 'Tháp của một lính canh. Xây rải rác quanh làng.',
      needs: 'Vũ khí và giáp cho lính.',
      tips: ['Chọn nghề Knight, Ranger hoặc Druid.', 'Mục Hostiles: chọn loại mob lính được đánh.', 'Guard Scepter: đặt điểm tuần tra.'],
      issues: ['mobs-kill', 'guards-attack-npc'] },
    { id: 'barracks', name: 'Barracks', img: 'barracks', stage: 4,
      role: 'Doanh trại nhiều lính, xây kèm các Barracks Tower.',
      needs: 'Vũ khí, giáp; nhiều dân rảnh để làm lính.',
      tips: ['Hợp làng lớn hoặc làng gần biển (Pirate tới bằng tàu).', 'Raid trên server tới khoảng 14 đêm một lần.'],
      issues: ['mobs-kill', 'guards-attack-npc'] },
    { id: 'hospital', name: 'Hospital', img: 'hospital', stage: 5,
      role: 'Healer chữa bệnh cho dân.',
      needs: 'Món chữa theo từng bệnh (Healer sẽ gửi yêu cầu).',
      tips: ['Để sẵn rau củ, bánh mì trong kho cho Healer.', 'Mức bệnh trên server là mặc định của mod.'],
      issues: ['unhappy'] },
    { id: 'school', name: 'School', img: 'school', stage: 5,
      role: 'Dạy trẻ con, giúp trẻ vui hơn và học kỹ năng trước khi đi làm.',
      needs: 'Giấy, sách cho giáo viên.',
      tips: ['Trẻ vào School thì vui hơn và lớn lên giỏi hơn.'],
      issues: ['no-children'] },
    { id: 'university', name: 'University', img: 'university', stage: 6,
      role: 'Nghiên cứu mở khoá công trình mới và tăng sức mạnh cả làng.',
      needs: 'Vật phẩm cho từng nghiên cứu (phải có sẵn trong túi khi bấm).',
      tips: ['3 nhánh: Civilian, Combat, Technology.', 'Huỷ nghiên cứu tốn 1 Ancient Tome.', 'Ưu tiên nghiên cứu tăng tốc thợ xây và Courier.'],
      issues: [] }
  ],

  items: [
    { id: 'supplycamp', name: 'Supply Camp', img: 'supplycamp', role: 'Đặt trên đất để lập thuộc địa. Có sẵn rương chứa Build Tool và Town Hall.' },
    { id: 'supplyship', name: 'Supply Ship', img: 'supplyship', role: 'Giống Supply Camp nhưng đặt trên mặt nước đủ rộng.' },
    { id: 'buildtool', name: 'Build Tool', img: 'buildtool', role: 'Chọn bản thiết kế và kiểu kiến trúc, xem trước rồi đặt công trình.' },
    { id: 'resourcescroll', name: 'Resource Scroll', img: 'resourcescroll', role: 'Nối với Builder\'s Hut, cho biết công trình đang xây còn thiếu gì.' },
    { id: 'clipboard', name: 'Clipboard', img: 'clipboard', role: 'Nối với Town Hall, liệt kê mọi yêu cầu đang chờ bạn đưa đồ.' },
    { id: 'guardscepter', name: 'Guard Scepter', img: 'guardscepter', role: 'Đặt điểm tuần tra hoặc điểm canh gác cho lính.' },
    { id: 'permissionscepter', name: 'Permission Scepter', img: 'permissionscepter', role: 'Đánh dấu block hoặc vị trí cho ai cũng dùng được (cổng, rương chung).' },
    { id: 'ancienttome', name: 'Ancient Tome', img: 'ancienttome', role: 'Vật phẩm hiếm, dùng để huỷ một nghiên cứu đã xong.' }
  ],

  issues: [
    { id: 'builder-idle', q: 'Thợ xây đứng im, không xây',
      steps: ['Mở Builder\'s Hut, xem danh sách vật liệu: thiếu món nào thì bỏ vào Warehouse hoặc rương của Builder\'s Hut.', 'So cấp: Builder\'s Hut phải có cấp bằng hoặc cao hơn công trình đang xây. Thấp hơn thì nâng cấp Builder\'s Hut trước.', 'Xem hàng đợi trong Builder\'s Hut: công trình khác có thể đang được ưu tiên.'] },
    { id: 'chest-ignored', q: 'Dân không dùng đồ trong rương tôi đặt',
      steps: ['Rương tự đặt không thuộc hệ thống của làng, dân không "thấy" nó.', 'Bỏ đồ vào Warehouse, hoặc vào rương nằm trong một công trình.', 'Dùng Stash nếu muốn một chỗ trả đồ để Courier tự mang về Warehouse.'] },
    { id: 'slow-delivery', q: 'Đồ giao chậm, thợ cứ "chờ"',
      steps: ['Làng thiếu Courier: xây thêm Courier\'s Hut hoặc nâng cấp nó.', 'Kiểm tra Warehouse còn chỗ trống không; kho đầy thì Courier không cất được.', 'Đường đi thông thoáng (rộng khoảng 3 block) giúp Courier đi nhanh, ít kẹt.'] },
    { id: 'unhappy', q: 'Dân buồn, làm việc chậm',
      steps: ['Mở Town Hall, xem điểm hạnh phúc để biết đang thiếu gì.', 'Thường gặp: đói, ăn mãi một món, thiếu nhà, công cụ hỏng, không có lính bảo vệ.', 'Thêm Dining Hall, Farm trồng nhiều loại, nâng cấp Residence.'] },
    { id: 'crafter-idle', q: 'Thợ chế tạo không làm món tôi cần',
      steps: ['Thợ chỉ làm các món có trong danh sách công thức của họ.', 'Vào giao diện công trình, tab công thức, thêm công thức bằng cách đặt nguyên liệu như bàn chế tạo.', 'Số công thức dạy được tăng theo cấp công trình.'] },
    { id: 'miner-idle', q: 'Thợ mỏ không đào',
      steps: ['Bỏ cuốc đúng cấp vào kho: thợ mỏ gửi yêu cầu nếu thiếu.', 'Chọn tầng đào trong giao diện Mine.', 'Kiểm tra đuốc và gỗ chống hầm trong kho.'] },
    { id: 'frozen', q: 'Làng "đứng hình" khi tôi đi xa',
      steps: ['Server chỉ giữ làng chạy khi chủ làng hoặc officer online và ở gần.', 'Thêm bạn bè làm officer: /mc colony addOfficer <id> <tên>, hoặc qua tab Permissions.', 'Không dùng chunk loader bên ngoài để ép làng chạy.'] },
    { id: 'mobs-kill', q: 'Quái vào làng giết dân',
      steps: ['Thắp sáng quanh làng để quái không mọc.', 'Xây Guard Tower sớm, rải quanh làng; dùng Guard Scepter đặt điểm tuần tra.', 'Trên server quái có tấn công dân, và raid tới khoảng 14 đêm một lần.'] },
    { id: 'no-children', q: 'Dân cưới nhau mà không sinh con',
      steps: ['Trẻ chỉ ra đời khi làng còn giường trống. Town Hall hiện "Needs Housing" là hết chỗ.', 'Nâng cấp hoặc xây thêm Residence: mỗi cấp thêm 1 giường, tối đa 5.', 'Town Hall, phần cài đặt: mục "Do children spawn" phải đang bật.', 'Trẻ cần ăn no và ngủ đủ mới lớn; School giúp trẻ vui hơn.', 'Muốn có dân ngay: tuyển khách ở Tavern.', 'Lưu ý: dân MCA cưới và có con theo luật riêng, không tính vào dân số MineColonies.'] },
    { id: 'guest-hostile', q: 'Người chơi khác bị lính đánh hoặc không mở được gì',
      steps: ['Chủ làng mở Town Hall, tab Permissions, thêm tên người đó.', 'Gán một cấp (rank) phù hợp; cấp kiểu Hostile thì lính sẽ tấn công.', 'Bật cho cấp đó các quyền cần: mở cửa và cổng, mở rương, chuột phải vào dân.', 'Muốn mở sẵn vài chỗ cho mọi người (cổng, rương chung): dùng Permission Scepter đánh dấu block tự do.'] },
    { id: 'guards-attack-npc', q: 'Lính đánh dân MCA hoặc động vật',
      steps: ['Mở giao diện Guard Tower hoặc Barracks, mục Hostiles.', 'Tắt những loại không muốn lính đánh, chỉ để lại quái.'] },
    { id: 'border', q: 'Không biết lãnh thổ làng tới đâu',
      steps: ['Đứng ở chỗ cần xem và gõ /mc whereami.', 'Game cho biết bạn đang ở thuộc địa nào và cách Town Hall bao xa.', 'Viền lãnh thổ không hiện trên bản đồ Xaero (MineColonies chỉ vẽ viền cho JourneyMap).'] },
    { id: 'no-trade', q: 'Không trade được với dân',
      steps: ['Dân MineColonies không buôn bán, đó là thiết kế của mod.', 'Muốn trade: dùng dân làng vanilla hoặc dân MCA.', 'Thứ gần với trade nhất: khách ở Tavern, trả đúng món họ đòi thì họ ở lại làm dân.'] },
    { id: 'no-control', q: 'Không ra lệnh được cho dân',
      steps: ['MineColonies không điều khiển từng người như dân vanilla.', 'Gán người vào công trình (tab Workers): họ làm nghề của công trình đó.', 'Chỉnh cài đặt của công trình: ruộng trồng gì, mỏ đào tầng nào, thợ làm món nào, lính tuần tra ở đâu.'] }
  ],

  settings: [
    ['Số thuộc địa mỗi người', '1', 'Chọn chỗ lập làng thật kỹ'],
    ['Dân khởi đầu', '4', ''],
    ['Dân tối đa', '250', ''],
    ['Vùng thuộc địa', '4 chunk lúc đầu, tối đa 20', 'Mở rộng theo công trình và cấp'],
    ['Khoảng cách giữa 2 làng', 'Ít nhất 8 chunk', ''],
    ['Raid', 'Khoảng 14 đêm một lần, độ khó 5/10', 'Raider phá được block và cửa'],
    ['Quái tấn công dân', 'Có', 'Thắp sáng và có lính'],
    ['Nổ trong thuộc địa', 'Chỉ gây sát thương', 'Creeper không phá nhà'],
    ['Giữ làng chạy khi vắng', 'Khi chủ hoặc officer online và ở gần', 'Thêm officer để giữ làng'],
    ['Thợ làm việc khi mưa', 'Không', 'Trời mưa là dân nghỉ'],
    ['Huỷ nghiên cứu', '1 Ancient Tome', ''],
    ['Dịch chuyển tới làng đồng minh', 'Khi Town Hall đạt cấp 3', ''],
    ['Lệnh dịch chuyển khác (home, rtp)', 'Tắt', '']
  ],

  // Item flow map: producers -> Warehouse (+ Courier) -> consumers; the player fills requests.
  flow: {
    producers: ['forester', 'farmer', 'miner'],
    consumers: ['builder', 'cook', 'guardtower']
  }
};
